### ISSUE TITLE
1.0.0 checklist

### ISSUE THREAD

**Issue by Underrout** [Underrout/callisto#91]
- [ ] Extract insertion/extraction functions from extractables/insertables
- [ ] Consider combining extractables and insertables into single classes
- [ ] Clarify builder classes
- [ ] Probably get rid of "convenience setup", easier to just use a baserom anyway
- [ ] Improve eloper stability
- [ ] #17 
- [ ] #36 
- [ ] #44 
- [ ] Potentially extract modules into a separate tool that can still be statically linked into callisto
- [ ] #63 (but extracting a tool for modules might also solve this on its own)
- [ ] #74 (maybe, no clue how this works)
- [ ] #69 
- [ ] #75 
- [ ] Consider leaving eloper injection strings in usertoolbar.txt so that Eloper will run even if LM is not launched through callisto
- [ ] Improve eloper/callisto resiliency to other instances of themselves via better interprocess communication (see also #82)
- [ ] #80 
- [ ] #84
- [ ] #90
